import { NextRequest } from 'next/server';
import { getRecord } from '@/lib/store';
import type { ExportRequest } from '@/lib/types';

function htmlToNextjsComponent(html: string, businessName: string): string {
  // Escape backticks and template literals for the template string
  const escaped = html
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');

  const componentName = businessName
    .replace(/[^a-zA-Z0-9\s]/g, '')
    .split(' ')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('');

  return `// Generated by PageForge — pageforge.vercel.app
// Business: ${businessName}
// Generated: ${new Date().toISOString()}

export default function ${componentName || 'LandingPage'}Page() {
  return (
    <div
      dangerouslySetInnerHTML={{
        __html: \`${escaped}\`,
      }}
    />
  );
}
`;
}

function addWatermark(html: string): string {
  const watermark = `
<!-- PageForge Watermark - Free Tier -->
<div style="position:fixed;bottom:16px;right:16px;z-index:9999;background:rgba(0,0,0,0.8);color:white;padding:8px 16px;border-radius:8px;font-family:sans-serif;font-size:12px;text-decoration:none;" >
  Built with <a href="https://pageforge.vercel.app" style="color:#818cf8;text-decoration:none;" target="_blank">PageForge</a>
</div>`;
  return html.replace('</body>', `${watermark}\n</body>`);
}

export async function POST(request: NextRequest) {
  try {
    const body = (await request.json()) as ExportRequest;
    const { generationId, format } = body;

    if (!generationId) {
      return Response.json({ error: 'generationId is required' }, { status: 400 });
    }

    const record = getRecord(generationId);
    if (!record) {
      return Response.json({ error: 'Generation not found' }, { status: 404 });
    }

    const isPaid = record.isPaid;

    if (format === 'html') {
      const html = isPaid
        ? record.result.html
        : addWatermark(record.result.html);

      return new Response(html, {
        headers: {
          'Content-Type': 'text/html',
          'Content-Disposition': `attachment; filename="${record.input.businessName.replace(/\s+/g, '-').toLowerCase()}-landing.html"`,
        },
      });
    }

    // nextjs format
    let code = htmlToNextjsComponent(record.result.html, record.input.businessName);

    if (!isPaid) {
      code = `// ⚠️  FREE TIER EXPORT — Watermark included
// Upgrade to PageForge Pro ($29/page) to remove watermark
// Visit: https://pageforge.vercel.app/generate

` + code;
    }

    return new Response(code, {
      headers: {
        'Content-Type': 'text/plain',
        'Content-Disposition': `attachment; filename="page.tsx"`,
      },
    });
  } catch (error) {
    console.error('Export error:', error);
    return Response.json({ error: 'Export failed' }, { status: 500 });
  }
}
