// tailwind.config.ts
// Design System: AI-POWERED LANDING PAGE GENERATOR FOR BUSINESSES, SAAS, AND CREATORS. ONE-CLICK PROFESSIONAL PAGES WITH AI COPY, MODERN DESIGN, AND CONVERSION OPTIMIZATION.
// Category: SaaS (General) | Style: Glassmorphism
// Generated by design-gen

import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        border:       "hsl(var(--color-border))",
        input:        "hsl(var(--color-border))",
        ring:         "hsl(var(--color-ring))",
        background:   "hsl(var(--color-background))",
        foreground:   "hsl(var(--color-foreground))",
        primary: {
          DEFAULT:    "#7C3AED",
          foreground: "#FFFFFF",
        },
        secondary: {
          DEFAULT:    "#6366F1",
          foreground: "#FFFFFF",
        },
        accent: {
          DEFAULT:    "#EC4899",
          foreground: "#FFFFFF",
        },
        destructive: {
          DEFAULT:    "#DC2626",
          foreground: "#FFFFFF",
        },
        muted: {
          DEFAULT:    "#F7F3FD",
          foreground: "#64748B",
        },
        card: {
          DEFAULT:    "#FFFFFF",
          foreground: "#0F172A",
        },
        // Brand raw tokens
        brand: "#7C3AED",
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      borderRadius: {
        lg:   '0.75rem',
        md:   '0.5rem',
        sm:   '0.25rem',
        xl:   '1rem',
        '2xl': '1.5rem',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to:   { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to:   { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0", transform: "translateY(8px)" },
          to:   { opacity: "1", transform: "translateY(0)" },
        },
        "slide-in": {
          from: { transform: "translateX(-100%)" },
          to:   { transform: "translateX(0)" },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up':   'accordion-up 0.2s ease-out',
        'fade-in':        'fade-in 0.25s ease-out',
        'slide-in':       'slide-in 0.3s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};

export default config;